spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    open-in-view: false
    properties:
      org.hibernate.envers.revision_field_name: rev_id
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.do_not_audit_optimistic_locking_field: false
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    db:
      writer:
        driver-class-name: org.postgresql.Driver
        auto-commit: false
        connection-timeout: 3000
        maximum-pool-size: 50
        max-lifetime: 50000
        pool-name: HikariCP-Writer
        jdbc-url: ${SPRING_DATASOURCE_DB_URL:}
        username: ${SPRING_DATASOURCE_DB_USERNAME:sa}
        password: ${SPRING_DATASOURCE_DB_PASSWORD:}
        initialization-mode: always
      reader:
        driver-class-name: org.postgresql.Driver
        auto-commit: true
        connection-timeout: 3000
        max-lifetime: 50000
        maximum-pool-size: 50
        pool-name: HikariCP-Reader
        jdbc-url: ${SPRING_DATASOURCE_READER_DB_URL:}
        username: ${SPRING_DATASOURCE_DB_USERNAME:sa}
        password: ${SPRING_DATASOURCE_DB_PASSWORD:}
        initialization-mode: always

---
spring:
  config.activate.on-profile: local
  datasource:
    db:
      writer:
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
        jdbc-url: jdbc:tc:postgresql:14.6:///test
        maximum-pool-size: 10
      reader:
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
        jdbc-url: jdbc:tc:postgresql:14.6:///test
        maximum-pool-size: 10
  jpa:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

---
spring:
  config.activate.on-profile: dev
  jpa:
    hibernate:
      format_sql: true

---
spring:
  config.activate.on-profile: beta
  jpa:
    hibernate.show-sql: true

---
spring:
  config.activate.on-profile: prod
